//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FormResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        internal static string account_code {
            get {
                return ResourceManager.GetString("account_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        internal static string account_id {
            get {
                return ResourceManager.GetString("account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Code.
        /// </summary>
        internal static string account_master_code {
            get {
                return ResourceManager.GetString("account_master_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Id.
        /// </summary>
        internal static string account_master_id {
            get {
                return ResourceManager.GetString("account_master_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Name.
        /// </summary>
        internal static string account_master_name {
            get {
                return ResourceManager.GetString("account_master_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id.
        /// </summary>
        internal static string activity_id {
            get {
                return ResourceManager.GetString("activity_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string address_line_1 {
            get {
                return ResourceManager.GetString("address_line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string address_line_2 {
            get {
                return ResourceManager.GetString("address_line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Slab Id.
        /// </summary>
        internal static string ageing_slab_id {
            get {
                return ResourceManager.GetString("ageing_slab_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Slab Name.
        /// </summary>
        internal static string ageing_slab_name {
            get {
                return ResourceManager.GetString("ageing_slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Bonus Setup Id.
        /// </summary>
        internal static string agent_bonus_setup_id {
            get {
                return ResourceManager.GetString("agent_bonus_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Code.
        /// </summary>
        internal static string agent_code {
            get {
                return ResourceManager.GetString("agent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Id.
        /// </summary>
        internal static string agent_id {
            get {
                return ResourceManager.GetString("agent_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        internal static string agent_name {
            get {
                return ResourceManager.GetString("agent_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Credit.
        /// </summary>
        internal static string allow_credit {
            get {
                return ResourceManager.GetString("allow_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Sales.
        /// </summary>
        internal static string allow_sales {
            get {
                return ResourceManager.GetString("allow_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount From.
        /// </summary>
        internal static string amount_from {
            get {
                return ResourceManager.GetString("amount_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To.
        /// </summary>
        internal static string amount_to {
            get {
                return ResourceManager.GetString("amount_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Count.
        /// </summary>
        internal static string analyze_count {
            get {
                return ResourceManager.GetString("analyze_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned By User Id.
        /// </summary>
        internal static string assigned_by_user_id {
            get {
                return ResourceManager.GetString("assigned_by_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Timestamp.
        /// </summary>
        internal static string audit_ts {
            get {
                return ResourceManager.GetString("audit_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit User Id.
        /// </summary>
        internal static string audit_user_id {
            get {
                return ResourceManager.GetString("audit_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoanalyze Count.
        /// </summary>
        internal static string autoanalyze_count {
            get {
                return ResourceManager.GetString("autoanalyze_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autovacuum Count.
        /// </summary>
        internal static string autovacuum_count {
            get {
                return ResourceManager.GetString("autovacuum_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Code.
        /// </summary>
        internal static string bank_account_code {
            get {
                return ResourceManager.GetString("bank_account_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Type.
        /// </summary>
        internal static string bank_account_type {
            get {
                return ResourceManager.GetString("bank_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Address.
        /// </summary>
        internal static string bank_address {
            get {
                return ResourceManager.GetString("bank_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        internal static string bank_branch {
            get {
                return ResourceManager.GetString("bank_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Contact Number.
        /// </summary>
        internal static string bank_contact_number {
            get {
                return ResourceManager.GetString("bank_contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string bank_name {
            get {
                return ResourceManager.GetString("bank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Quantity.
        /// </summary>
        internal static string base_quantity {
            get {
                return ResourceManager.GetString("base_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Unit Id.
        /// </summary>
        internal static string base_unit_id {
            get {
                return ResourceManager.GetString("base_unit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Unit Name.
        /// </summary>
        internal static string base_unit_name {
            get {
                return ResourceManager.GetString("base_unit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Rate.
        /// </summary>
        internal static string bonus_rate {
            get {
                return ResourceManager.GetString("bonus_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Code.
        /// </summary>
        internal static string bonus_slab_code {
            get {
                return ResourceManager.GetString("bonus_slab_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Detail Id.
        /// </summary>
        internal static string bonus_slab_detail_id {
            get {
                return ResourceManager.GetString("bonus_slab_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Id.
        /// </summary>
        internal static string bonus_slab_id {
            get {
                return ResourceManager.GetString("bonus_slab_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Name.
        /// </summary>
        internal static string bonus_slab_name {
            get {
                return ResourceManager.GetString("bonus_slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Code.
        /// </summary>
        internal static string brand_code {
            get {
                return ResourceManager.GetString("brand_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Id.
        /// </summary>
        internal static string brand_id {
            get {
                return ResourceManager.GetString("brand_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        internal static string brand_name {
            get {
                return ResourceManager.GetString("brand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Self Verify.
        /// </summary>
        internal static string can_self_verify {
            get {
                return ResourceManager.GetString("can_self_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Verify GL Transactions.
        /// </summary>
        internal static string can_verify_gl_transactions {
            get {
                return ResourceManager.GetString("can_verify_gl_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Verify Purchase Transactions.
        /// </summary>
        internal static string can_verify_purchase_transactions {
            get {
                return ResourceManager.GetString("can_verify_purchase_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Verify Sales Transactions.
        /// </summary>
        internal static string can_verify_sales_transactions {
            get {
                return ResourceManager.GetString("can_verify_sales_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Id.
        /// </summary>
        internal static string cashier_id {
            get {
                return ResourceManager.GetString("cashier_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository Code.
        /// </summary>
        internal static string cash_repository_code {
            get {
                return ResourceManager.GetString("cash_repository_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository Id.
        /// </summary>
        internal static string cash_repository_id {
            get {
                return ResourceManager.GetString("cash_repository_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository Name.
        /// </summary>
        internal static string cash_repository_name {
            get {
                return ResourceManager.GetString("cash_repository_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        internal static string cell {
            get {
                return ResourceManager.GetString("cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Interest.
        /// </summary>
        internal static string charge_interest {
            get {
                return ResourceManager.GetString("charge_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Frequency Id.
        /// </summary>
        internal static string checking_frequency_id {
            get {
                return ResourceManager.GetString("checking_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Default.
        /// </summary>
        internal static string column_default {
            get {
                return ResourceManager.GetString("column_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        internal static string column_name {
            get {
                return ResourceManager.GetString("column_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string commission_rate {
            get {
                return ResourceManager.GetString("commission_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Unit Id.
        /// </summary>
        internal static string compare_unit_id {
            get {
                return ResourceManager.GetString("compare_unit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Unit Name.
        /// </summary>
        internal static string compare_unit_name {
            get {
                return ResourceManager.GetString("compare_unit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Unit Id.
        /// </summary>
        internal static string compound_unit_id {
            get {
                return ResourceManager.GetString("compound_unit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        internal static string confidential {
            get {
                return ResourceManager.GetString("confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Cell.
        /// </summary>
        internal static string contact_cell {
            get {
                return ResourceManager.GetString("contact_cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact City.
        /// </summary>
        internal static string contact_city {
            get {
                return ResourceManager.GetString("contact_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Country.
        /// </summary>
        internal static string contact_country {
            get {
                return ResourceManager.GetString("contact_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        internal static string contact_email {
            get {
                return ResourceManager.GetString("contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string contact_number {
            get {
                return ResourceManager.GetString("contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string contact_person {
            get {
                return ResourceManager.GetString("contact_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        internal static string contact_phone {
            get {
                return ResourceManager.GetString("contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact State.
        /// </summary>
        internal static string contact_state {
            get {
                return ResourceManager.GetString("contact_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Street.
        /// </summary>
        internal static string contact_street {
            get {
                return ResourceManager.GetString("contact_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Code.
        /// </summary>
        internal static string cost_center_code {
            get {
                return ResourceManager.GetString("cost_center_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Id.
        /// </summary>
        internal static string cost_center_id {
            get {
                return ResourceManager.GetString("cost_center_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Name.
        /// </summary>
        internal static string cost_center_name {
            get {
                return ResourceManager.GetString("cost_center_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        internal static string cost_price {
            get {
                return ResourceManager.GetString("cost_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price Includes Tax.
        /// </summary>
        internal static string cost_price_includes_tax {
            get {
                return ResourceManager.GetString("cost_price_includes_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Code.
        /// </summary>
        internal static string counter_code {
            get {
                return ResourceManager.GetString("counter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Id.
        /// </summary>
        internal static string counter_id {
            get {
                return ResourceManager.GetString("counter_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Name.
        /// </summary>
        internal static string counter_name {
            get {
                return ResourceManager.GetString("counter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CST Number.
        /// </summary>
        internal static string cst_number {
            get {
                return ResourceManager.GetString("cst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string currency_code {
            get {
                return ResourceManager.GetString("currency_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string currency_name {
            get {
                return ResourceManager.GetString("currency_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        internal static string currency_symbol {
            get {
                return ResourceManager.GetString("currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        internal static string customer_code {
            get {
                return ResourceManager.GetString("customer_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        internal static string customer_id {
            get {
                return ResourceManager.GetString("customer_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string data_type {
            get {
                return ResourceManager.GetString("data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime Precision.
        /// </summary>
        internal static string datetime_precision {
            get {
                return ResourceManager.GetString("datetime_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string debit {
            get {
                return ResourceManager.GetString("debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string department_code {
            get {
                return ResourceManager.GetString("department_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Id.
        /// </summary>
        internal static string department_id {
            get {
                return ResourceManager.GetString("department_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string department_name {
            get {
                return ResourceManager.GetString("department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string domain_name {
            get {
                return ResourceManager.GetString("domain_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        internal static string effective_from {
            get {
                return ResourceManager.GetString("effective_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends On.
        /// </summary>
        internal static string ends_on {
            get {
                return ResourceManager.GetString("ends_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Timestamp.
        /// </summary>
        internal static string entry_ts {
            get {
                return ResourceManager.GetString("entry_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Timestamp.
        /// </summary>
        internal static string event_ts {
            get {
                return ResourceManager.GetString("event_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude From Purchase.
        /// </summary>
        internal static string exclude_from_purchase {
            get {
                return ResourceManager.GetString("exclude_from_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude From Sales.
        /// </summary>
        internal static string exclude_from_sales {
            get {
                return ResourceManager.GetString("exclude_from_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Code.
        /// </summary>
        internal static string external_code {
            get {
                return ResourceManager.GetString("external_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Address.
        /// </summary>
        internal static string factory_address {
            get {
                return ResourceManager.GetString("factory_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Date Time.
        /// </summary>
        internal static string failed_date_time {
            get {
                return ResourceManager.GetString("failed_date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Login Id.
        /// </summary>
        internal static string failed_login_id {
            get {
                return ResourceManager.GetString("failed_login_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year Code.
        /// </summary>
        internal static string fiscal_year_code {
            get {
                return ResourceManager.GetString("fiscal_year_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year Name.
        /// </summary>
        internal static string fiscal_year_name {
            get {
                return ResourceManager.GetString("fiscal_year_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Code.
        /// </summary>
        internal static string frequency_code {
            get {
                return ResourceManager.GetString("frequency_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Id.
        /// </summary>
        internal static string frequency_id {
            get {
                return ResourceManager.GetString("frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Name.
        /// </summary>
        internal static string frequency_name {
            get {
                return ResourceManager.GetString("frequency_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Setup Id.
        /// </summary>
        internal static string frequency_setup_id {
            get {
                return ResourceManager.GetString("frequency_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Days.
        /// </summary>
        internal static string from_days {
            get {
                return ResourceManager.GetString("from_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Verification Limit.
        /// </summary>
        internal static string gl_verification_limit {
            get {
                return ResourceManager.GetString("gl_verification_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Child.
        /// </summary>
        internal static string has_child {
            get {
                return ResourceManager.GetString("has_child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Item.
        /// </summary>
        internal static string hot_item {
            get {
                return ResourceManager.GetString("hot_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundredth Name.
        /// </summary>
        internal static string hundredth_name {
            get {
                return ResourceManager.GetString("hundredth_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Tax.
        /// </summary>
        internal static string includes_tax {
            get {
                return ResourceManager.GetString("includes_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Compounding Frequency Id.
        /// </summary>
        internal static string interest_compounding_frequency_id {
            get {
                return ResourceManager.GetString("interest_compounding_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        internal static string interest_rate {
            get {
                return ResourceManager.GetString("interest_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string ip_address {
            get {
                return ResourceManager.GetString("ip_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string is_active {
            get {
                return ResourceManager.GetString("is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Admin.
        /// </summary>
        internal static string is_admin {
            get {
                return ResourceManager.GetString("is_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Cash.
        /// </summary>
        internal static string is_cash {
            get {
                return ResourceManager.GetString("is_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Nullable.
        /// </summary>
        internal static string is_nullable {
            get {
                return ResourceManager.GetString("is_nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Supplier.
        /// </summary>
        internal static string is_supplier {
            get {
                return ResourceManager.GetString("is_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is System.
        /// </summary>
        internal static string is_system {
            get {
                return ResourceManager.GetString("is_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string item_code {
            get {
                return ResourceManager.GetString("item_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Cost Price Id.
        /// </summary>
        internal static string item_cost_price_id {
            get {
                return ResourceManager.GetString("item_cost_price_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group Code.
        /// </summary>
        internal static string item_group_code {
            get {
                return ResourceManager.GetString("item_group_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group Id.
        /// </summary>
        internal static string item_group_id {
            get {
                return ResourceManager.GetString("item_group_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group Name.
        /// </summary>
        internal static string item_group_name {
            get {
                return ResourceManager.GetString("item_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string item_id {
            get {
                return ResourceManager.GetString("item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Image.
        /// </summary>
        internal static string item_image {
            get {
                return ResourceManager.GetString("item_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Opening Inventory Id.
        /// </summary>
        internal static string item_opening_inventory_id {
            get {
                return ResourceManager.GetString("item_opening_inventory_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Selling Price Id.
        /// </summary>
        internal static string item_selling_price_id {
            get {
                return ResourceManager.GetString("item_selling_price_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Analaze.
        /// </summary>
        internal static string last_analyze {
            get {
                return ResourceManager.GetString("last_analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Autoanalyze.
        /// </summary>
        internal static string last_autoanalyze {
            get {
                return ResourceManager.GetString("last_autoanalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Autovacuum.
        /// </summary>
        internal static string last_autovacuum {
            get {
                return ResourceManager.GetString("last_autovacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Vacuum.
        /// </summary>
        internal static string last_vacuum {
            get {
                return ResourceManager.GetString("last_vacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Code.
        /// </summary>
        internal static string lead_source_code {
            get {
                return ResourceManager.GetString("lead_source_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Id.
        /// </summary>
        internal static string lead_source_id {
            get {
                return ResourceManager.GetString("lead_source_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Name.
        /// </summary>
        internal static string lead_source_name {
            get {
                return ResourceManager.GetString("lead_source_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Code.
        /// </summary>
        internal static string lead_status_code {
            get {
                return ResourceManager.GetString("lead_status_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Id.
        /// </summary>
        internal static string lead_status_id {
            get {
                return ResourceManager.GetString("lead_status_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Name.
        /// </summary>
        internal static string lead_status_name {
            get {
                return ResourceManager.GetString("lead_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time (In Days).
        /// </summary>
        internal static string lead_time_in_days {
            get {
                return ResourceManager.GetString("lead_time_in_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Out Id.
        /// </summary>
        internal static string lock_out_id {
            get {
                return ResourceManager.GetString("lock_out_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Out Till.
        /// </summary>
        internal static string lock_out_till {
            get {
                return ResourceManager.GetString("lock_out_till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Out Time.
        /// </summary>
        internal static string lock_out_time {
            get {
                return ResourceManager.GetString("lock_out_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In Office.
        /// </summary>
        internal static string logged_in_office {
            get {
                return ResourceManager.GetString("logged_in_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In Office Id.
        /// </summary>
        internal static string logged_in_office_id {
            get {
                return ResourceManager.GetString("logged_in_office_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Date Time.
        /// </summary>
        internal static string login_date_time {
            get {
                return ResourceManager.GetString("login_date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Id.
        /// </summary>
        internal static string login_id {
            get {
                return ResourceManager.GetString("login_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintained By.
        /// </summary>
        internal static string maintained_by {
            get {
                return ResourceManager.GetString("maintained_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintained By User Id.
        /// </summary>
        internal static string maintained_by_user_id {
            get {
                return ResourceManager.GetString("maintained_by_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Stock.
        /// </summary>
        internal static string maintain_stock {
            get {
                return ResourceManager.GetString("maintain_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Credit Amount.
        /// </summary>
        internal static string maximum_credit_amount {
            get {
                return ResourceManager.GetString("maximum_credit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Credit Period.
        /// </summary>
        internal static string maximum_credit_period {
            get {
                return ResourceManager.GetString("maximum_credit_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Code.
        /// </summary>
        internal static string menu_code {
            get {
                return ResourceManager.GetString("menu_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Id.
        /// </summary>
        internal static string menu_id {
            get {
                return ResourceManager.GetString("menu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Text.
        /// </summary>
        internal static string menu_text {
            get {
                return ResourceManager.GetString("menu_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string middle_name {
            get {
                return ResourceManager.GetString("middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Credit.
        /// </summary>
        internal static string mimimum_credit_amount {
            get {
                return ResourceManager.GetString("mimimum_credit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Val.
        /// </summary>
        internal static string new_val {
            get {
                return ResourceManager.GetString("new_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        internal static string nick_name {
            get {
                return ResourceManager.GetString("nick_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Precision.
        /// </summary>
        internal static string numeric_precision {
            get {
                return ResourceManager.GetString("numeric_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Precision Radix.
        /// </summary>
        internal static string numeric_precision_radix {
            get {
                return ResourceManager.GetString("numeric_precision_radix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Scale.
        /// </summary>
        internal static string numeric_scale {
            get {
                return ResourceManager.GetString("numeric_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        internal static string office_address {
            get {
                return ResourceManager.GetString("office_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Code.
        /// </summary>
        internal static string office_code {
            get {
                return ResourceManager.GetString("office_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Id.
        /// </summary>
        internal static string office_id {
            get {
                return ResourceManager.GetString("office_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Name.
        /// </summary>
        internal static string office_name {
            get {
                return ResourceManager.GetString("office_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Val.
        /// </summary>
        internal static string old_val {
            get {
                return ResourceManager.GetString("old_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Code.
        /// </summary>
        internal static string opportunity_stage_code {
            get {
                return ResourceManager.GetString("opportunity_stage_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Id.
        /// </summary>
        internal static string opportunity_stage_id {
            get {
                return ResourceManager.GetString("opportunity_stage_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Name.
        /// </summary>
        internal static string opportunity_stage_name {
            get {
                return ResourceManager.GetString("opportunity_stage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal Position.
        /// </summary>
        internal static string ordinal_position {
            get {
                return ResourceManager.GetString("ordinal_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number.
        /// </summary>
        internal static string pan_number {
            get {
                return ResourceManager.GetString("pan_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Code.
        /// </summary>
        internal static string parent_account_code {
            get {
                return ResourceManager.GetString("parent_account_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Id.
        /// </summary>
        internal static string parent_account_id {
            get {
                return ResourceManager.GetString("parent_account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Name.
        /// </summary>
        internal static string parent_account_name {
            get {
                return ResourceManager.GetString("parent_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Cash Repository Id.
        /// </summary>
        internal static string parent_cash_repository_id {
            get {
                return ResourceManager.GetString("parent_cash_repository_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Cr Code.
        /// </summary>
        internal static string parent_cr_code {
            get {
                return ResourceManager.GetString("parent_cr_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Cr Name.
        /// </summary>
        internal static string parent_cr_name {
            get {
                return ResourceManager.GetString("parent_cr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Menu Id.
        /// </summary>
        internal static string parent_menu_id {
            get {
                return ResourceManager.GetString("parent_menu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Office Id.
        /// </summary>
        internal static string parent_office_id {
            get {
                return ResourceManager.GetString("parent_office_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string party {
            get {
                return ResourceManager.GetString("party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Code.
        /// </summary>
        internal static string party_code {
            get {
                return ResourceManager.GetString("party_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Id.
        /// </summary>
        internal static string party_id {
            get {
                return ResourceManager.GetString("party_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name.
        /// </summary>
        internal static string party_name {
            get {
                return ResourceManager.GetString("party_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type.
        /// </summary>
        internal static string party_type {
            get {
                return ResourceManager.GetString("party_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Code.
        /// </summary>
        internal static string party_type_code {
            get {
                return ResourceManager.GetString("party_type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Id.
        /// </summary>
        internal static string party_type_id {
            get {
                return ResourceManager.GetString("party_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Name.
        /// </summary>
        internal static string party_type_name {
            get {
                return ResourceManager.GetString("party_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Supplier Id.
        /// </summary>
        internal static string preferred_supplier_id {
            get {
                return ResourceManager.GetString("preferred_supplier_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type.
        /// </summary>
        internal static string price_type {
            get {
                return ResourceManager.GetString("price_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type Code.
        /// </summary>
        internal static string price_type_code {
            get {
                return ResourceManager.GetString("price_type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type Id.
        /// </summary>
        internal static string price_type_id {
            get {
                return ResourceManager.GetString("price_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type Name.
        /// </summary>
        internal static string price_type_name {
            get {
                return ResourceManager.GetString("price_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key Id.
        /// </summary>
        internal static string primary_key_id {
            get {
                return ResourceManager.GetString("primary_key_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal User.
        /// </summary>
        internal static string principal_user {
            get {
                return ResourceManager.GetString("principal_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Verification Limit.
        /// </summary>
        internal static string purchase_verification_limit {
            get {
                return ResourceManager.GetString("purchase_verification_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Per Base Quantity.
        /// </summary>
        internal static string rate_per_base_quantity {
            get {
                return ResourceManager.GetString("rate_per_base_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Per Quantity.
        /// </summary>
        internal static string rate_per_quantity {
            get {
                return ResourceManager.GetString("rate_per_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References Field.
        /// </summary>
        internal static string references_field {
            get {
                return ResourceManager.GetString("references_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References Schema.
        /// </summary>
        internal static string references_schema {
            get {
                return ResourceManager.GetString("references_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References Table.
        /// </summary>
        internal static string references_table {
            get {
                return ResourceManager.GetString("references_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        internal static string reference_number {
            get {
                return ResourceManager.GetString("reference_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        internal static string ref_no {
            get {
                return ResourceManager.GetString("ref_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string registration_date {
            get {
                return ResourceManager.GetString("registration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        internal static string registration_number {
            get {
                return ResourceManager.GetString("registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Officer Name.
        /// </summary>
        internal static string relationship_officer_name {
            get {
                return ResourceManager.GetString("relationship_officer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Officer.
        /// </summary>
        internal static string relation_officer {
            get {
                return ResourceManager.GetString("relation_officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Name.
        /// </summary>
        internal static string relname {
            get {
                return ResourceManager.GetString("relname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote User.
        /// </summary>
        internal static string remote_user {
            get {
                return ResourceManager.GetString("remote_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        internal static string reorder_level {
            get {
                return ResourceManager.GetString("reorder_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string repository {
            get {
                return ResourceManager.GetString("repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code.
        /// </summary>
        internal static string role_code {
            get {
                return ResourceManager.GetString("role_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        internal static string role_id {
            get {
                return ResourceManager.GetString("role_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string role_name {
            get {
                return ResourceManager.GetString("role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Verification Limit.
        /// </summary>
        internal static string sales_verification_limit {
            get {
                return ResourceManager.GetString("sales_verification_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selft Verification Limit.
        /// </summary>
        internal static string self_verification_limit {
            get {
                return ResourceManager.GetString("self_verification_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string selling_price {
            get {
                return ResourceManager.GetString("selling_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price Includes Tax.
        /// </summary>
        internal static string selling_price_includes_tax {
            get {
                return ResourceManager.GetString("selling_price_includes_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Code.
        /// </summary>
        internal static string shipper_code {
            get {
                return ResourceManager.GetString("shipper_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Id.
        /// </summary>
        internal static string shipper_id {
            get {
                return ResourceManager.GetString("shipper_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Name.
        /// </summary>
        internal static string shipper_name {
            get {
                return ResourceManager.GetString("shipper_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string shipping_address {
            get {
                return ResourceManager.GetString("shipping_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Code.
        /// </summary>
        internal static string shipping_address_code {
            get {
                return ResourceManager.GetString("shipping_address_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Id.
        /// </summary>
        internal static string shipping_address_id {
            get {
                return ResourceManager.GetString("shipping_address_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab Name.
        /// </summary>
        internal static string slab_name {
            get {
                return ResourceManager.GetString("slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SST Number.
        /// </summary>
        internal static string sst_number {
            get {
                return ResourceManager.GetString("sst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts From.
        /// </summary>
        internal static string starts_from {
            get {
                return ResourceManager.GetString("starts_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Reference.
        /// </summary>
        internal static string statement_reference {
            get {
                return ResourceManager.GetString("statement_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Master Detail Id.
        /// </summary>
        internal static string stock_master_detail_id {
            get {
                return ResourceManager.GetString("stock_master_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Master Id.
        /// </summary>
        internal static string stock_master_id {
            get {
                return ResourceManager.GetString("stock_master_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Master Rate Id.
        /// </summary>
        internal static string stock_master_rate_id {
            get {
                return ResourceManager.GetString("stock_master_rate_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        internal static string store_code {
            get {
                return ResourceManager.GetString("store_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Id.
        /// </summary>
        internal static string store_id {
            get {
                return ResourceManager.GetString("store_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string store_name {
            get {
                return ResourceManager.GetString("store_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Policy Detail Id.
        /// </summary>
        internal static string store_policy_detail_id {
            get {
                return ResourceManager.GetString("store_policy_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Policy Id.
        /// </summary>
        internal static string store_policy_id {
            get {
                return ResourceManager.GetString("store_policy_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Code.
        /// </summary>
        internal static string store_type_code {
            get {
                return ResourceManager.GetString("store_type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Id.
        /// </summary>
        internal static string store_type_id {
            get {
                return ResourceManager.GetString("store_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Name.
        /// </summary>
        internal static string store_type_name {
            get {
                return ResourceManager.GetString("store_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string sub_total {
            get {
                return ResourceManager.GetString("sub_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        internal static string supplier_code {
            get {
                return ResourceManager.GetString("supplier_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Id.
        /// </summary>
        internal static string supplier_id {
            get {
                return ResourceManager.GetString("supplier_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string supplier_name {
            get {
                return ResourceManager.GetString("supplier_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys Type.
        /// </summary>
        internal static string sys_type {
            get {
                return ResourceManager.GetString("sys_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys User Id.
        /// </summary>
        internal static string sys_user_id {
            get {
                return ResourceManager.GetString("sys_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        internal static string table_name {
            get {
                return ResourceManager.GetString("table_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Schema.
        /// </summary>
        internal static string table_schema {
            get {
                return ResourceManager.GetString("table_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        internal static string tax_amount {
            get {
                return ResourceManager.GetString("tax_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string tax_code {
            get {
                return ResourceManager.GetString("tax_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string tax_id {
            get {
                return ResourceManager.GetString("tax_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string tax_name {
            get {
                return ResourceManager.GetString("tax_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type Code.
        /// </summary>
        internal static string tax_type_code {
            get {
                return ResourceManager.GetString("tax_type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type Id.
        /// </summary>
        internal static string tax_type_id {
            get {
                return ResourceManager.GetString("tax_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type Name.
        /// </summary>
        internal static string tax_type_name {
            get {
                return ResourceManager.GetString("tax_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Days.
        /// </summary>
        internal static string to_days {
            get {
                return ResourceManager.GetString("to_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        internal static string transaction_code {
            get {
                return ResourceManager.GetString("transaction_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Counter.
        /// </summary>
        internal static string transaction_counter {
            get {
                return ResourceManager.GetString("transaction_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string transaction_date {
            get {
                return ResourceManager.GetString("transaction_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Detail Id.
        /// </summary>
        internal static string transaction_detail_id {
            get {
                return ResourceManager.GetString("transaction_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Master Id.
        /// </summary>
        internal static string transaction_master_id {
            get {
                return ResourceManager.GetString("transaction_master_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Ts.
        /// </summary>
        internal static string transaction_ts {
            get {
                return ResourceManager.GetString("transaction_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string transaction_type {
            get {
                return ResourceManager.GetString("transaction_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDT Name.
        /// </summary>
        internal static string udt_name {
            get {
                return ResourceManager.GetString("udt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Code.
        /// </summary>
        internal static string unit_code {
            get {
                return ResourceManager.GetString("unit_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string unit_id {
            get {
                return ResourceManager.GetString("unit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string unit_name {
            get {
                return ResourceManager.GetString("unit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string user_id {
            get {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Count.
        /// </summary>
        internal static string vacuum_count {
            get {
                return ResourceManager.GetString("vacuum_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Date.
        /// </summary>
        internal static string value_date {
            get {
                return ResourceManager.GetString("value_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string verification {
            get {
                return ResourceManager.GetString("verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify GL Transactions.
        /// </summary>
        internal static string verify_gl_transactions {
            get {
                return ResourceManager.GetString("verify_gl_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Purchase Transactions.
        /// </summary>
        internal static string verify_purchase_transactions {
            get {
                return ResourceManager.GetString("verify_purchase_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Sales Transactions.
        /// </summary>
        internal static string verify_sales_transactions {
            get {
                return ResourceManager.GetString("verify_sales_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workcenter Code.
        /// </summary>
        internal static string work_center_code {
            get {
                return ResourceManager.GetString("work_center_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workcenter Id.
        /// </summary>
        internal static string work_center_id {
            get {
                return ResourceManager.GetString("work_center_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workcenter Name.
        /// </summary>
        internal static string work_center_name {
            get {
                return ResourceManager.GetString("work_center_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written By User Id.
        /// </summary>
        internal static string written_by_user_id {
            get {
                return ResourceManager.GetString("written_by_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string zip_code {
            get {
                return ResourceManager.GetString("zip_code", resourceCulture);
            }
        }
    }
}
