//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Titles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        internal static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Entry.
        /// </summary>
        internal static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Slab Setup.
        /// </summary>
        internal static string AgeingSlabSetup {
            get {
                return ResourceManager.GetString("AgeingSlabSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Bonus Slab Assignment.
        /// </summary>
        internal static string AgentBonusSlabAssignment {
            get {
                return ResourceManager.GetString("AgentBonusSlabAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Bonus Slabs.
        /// </summary>
        internal static string AgentBonusSlabs {
            get {
                return ResourceManager.GetString("AgentBonusSlabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Setup.
        /// </summary>
        internal static string AgentSetup {
            get {
                return ResourceManager.GetString("AgentSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Databse.
        /// </summary>
        internal static string AnalyzeDatabse {
            get {
                return ResourceManager.GetString("AnalyzeDatabse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Verification Policy.
        /// </summary>
        internal static string AutoVerificationPolicy {
            get {
                return ResourceManager.GetString("AutoVerificationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        internal static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Details.
        /// </summary>
        internal static string BonusSlabDetails {
            get {
                return ResourceManager.GetString("BonusSlabDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repositories.
        /// </summary>
        internal static string CashRepositories {
            get {
                return ResourceManager.GetString("CashRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository.
        /// </summary>
        internal static string CashRepository {
            get {
                return ResourceManager.GetString("CashRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository Balance.
        /// </summary>
        internal static string CashRepositoryBalance {
            get {
                return ResourceManager.GetString("CashRepositoryBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        internal static string ChartOfAccounts {
            get {
                return ResourceManager.GetString("ChartOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklists.
        /// </summary>
        internal static string Checklists {
            get {
                return ResourceManager.GetString("Checklists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Units of Measure.
        /// </summary>
        internal static string CompoundUnitsOfMeasure {
            get {
                return ResourceManager.GetString("CompoundUnitsOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centers.
        /// </summary>
        internal static string CostCenters {
            get {
                return ResourceManager.GetString("CostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        internal static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Total.
        /// </summary>
        internal static string CreditTotal {
            get {
                return ResourceManager.GetString("CreditTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        internal static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer PAN Number.
        /// </summary>
        internal static string CustomerPanNumber {
            get {
                return ResourceManager.GetString("CustomerPanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Statistics.
        /// </summary>
        internal static string DatabaseStatistics {
            get {
                return ResourceManager.GetString("DatabaseStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Total.
        /// </summary>
        internal static string DebitTotal {
            get {
                return ResourceManager.GetString("DebitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        internal static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver To.
        /// </summary>
        internal static string DeliverTo {
            get {
                return ResourceManager.GetString("DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Without Sales Order.
        /// </summary>
        internal static string DeliveryWithoutSalesOrder {
            get {
                return ResourceManager.GetString("DeliveryWithoutSalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Purchase.
        /// </summary>
        internal static string DirectPurchase {
            get {
                return ResourceManager.GetString("DirectPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Sales.
        /// </summary>
        internal static string DirectSales {
            get {
                return ResourceManager.GetString("DirectSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr.
        /// </summary>
        internal static string Dr {
            get {
                return ResourceManager.GetString("Dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected.
        /// </summary>
        internal static string EditSelected {
            get {
                return ResourceManager.GetString("EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email This Invoice.
        /// </summary>
        internal static string EmailThisInvoice {
            get {
                return ResourceManager.GetString("EmailThisInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered By.
        /// </summary>
        internal static string EnteredBy {
            get {
                return ResourceManager.GetString("EnteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Selection.
        /// </summary>
        internal static string FlagSelection {
            get {
                return ResourceManager.GetString("FlagSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies.
        /// </summary>
        internal static string Frequencies {
            get {
                return ResourceManager.GetString("Frequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Advice.
        /// </summary>
        internal static string GLAdvice {
            get {
                return ResourceManager.GetString("GLAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Details.
        /// </summary>
        internal static string GLDetails {
            get {
                return ResourceManager.GetString("GLDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receipt Note.
        /// </summary>
        internal static string GoodsReceiptNote {
            get {
                return ResourceManager.GetString("GoodsReceiptNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Top.
        /// </summary>
        internal static string GoToTop {
            get {
                return ResourceManager.GetString("GoToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount.
        /// </summary>
        internal static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        internal static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Cost Prices.
        /// </summary>
        internal static string ItemCostPrices {
            get {
                return ResourceManager.GetString("ItemCostPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Groups.
        /// </summary>
        internal static string ItemGroups {
            get {
                return ResourceManager.GetString("ItemGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Selling Prices.
        /// </summary>
        internal static string ItemSellingPrices {
            get {
                return ResourceManager.GetString("ItemSellingPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Voucher Entry.
        /// </summary>
        internal static string JournalVoucherEntry {
            get {
                return ResourceManager.GetString("JournalVoucherEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Sources.
        /// </summary>
        internal static string LeadSources {
            get {
                return ResourceManager.GetString("LeadSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Statuses.
        /// </summary>
        internal static string LeadStatuses {
            get {
                return ResourceManager.GetString("LeadStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login View.
        /// </summary>
        internal static string LoginView {
            get {
                return ResourceManager.GetString("LoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge and Convert Batch to Sales Delivery.
        /// </summary>
        internal static string MergeBatchConvertToSalesDelivery {
            get {
                return ResourceManager.GetString("MergeBatchConvertToSalesDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Batch to Sales Delivery.
        /// </summary>
        internal static string MergeBatchToSalesDelivery {
            get {
                return ResourceManager.GetString("MergeBatchToSalesDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Batch to Sales Order.
        /// </summary>
        internal static string MergeBatchToSalesOrder {
            get {
                return ResourceManager.GetString("MergeBatchToSalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Code.
        /// </summary>
        internal static string OfficeCode {
            get {
                return ResourceManager.GetString("OfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Setup.
        /// </summary>
        internal static string OfficeSetup {
            get {
                return ResourceManager.GetString("OfficeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stages.
        /// </summary>
        internal static string OpportunityStages {
            get {
                return ResourceManager.GetString("OpportunityStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        internal static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Number.
        /// </summary>
        internal static string PanNumber {
            get {
                return ResourceManager.GetString("PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Maintenance.
        /// </summary>
        internal static string PartyMaintenance {
            get {
                return ResourceManager.GetString("PartyMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Types.
        /// </summary>
        internal static string PartyTypes {
            get {
                return ResourceManager.GetString("PartyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Transaction.
        /// </summary>
        internal static string PostTransaction {
            get {
                return ResourceManager.GetString("PostTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared On.
        /// </summary>
        internal static string PreparedOn {
            get {
                return ResourceManager.GetString("PreparedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type.
        /// </summary>
        internal static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed On.
        /// </summary>
        internal static string PrintedOn {
            get {
                return ResourceManager.GetString("PrintedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print GL Entry.
        /// </summary>
        internal static string PrintGLEntry {
            get {
                return ResourceManager.GetString("PrintGLEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Receipt.
        /// </summary>
        internal static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print This Invoice.
        /// </summary>
        internal static string PrintThisInvoice {
            get {
                return ResourceManager.GetString("PrintThisInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice.
        /// </summary>
        internal static string PurchaseInvoice {
            get {
                return ResourceManager.GetString("PurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Type.
        /// </summary>
        internal static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string QuantityAbbreviated {
            get {
                return ResourceManager.GetString("QuantityAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        internal static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref#.
        /// </summary>
        internal static string ReferenceNumberAbbreviated {
            get {
                return ResourceManager.GetString("ReferenceNumberAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Not Found.
        /// </summary>
        internal static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Maintenance.
        /// </summary>
        internal static string RoleMaintenance {
            get {
                return ResourceManager.GetString("RoleMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Total.
        /// </summary>
        internal static string RunningTotal {
            get {
                return ResourceManager.GetString("RunningTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Delivery.
        /// </summary>
        internal static string SalesDelivery {
            get {
                return ResourceManager.GetString("SalesDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Delivery Note.
        /// </summary>
        internal static string SalesDeliveryNote {
            get {
                return ResourceManager.GetString("SalesDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        internal static string SalesInvoice {
            get {
                return ResourceManager.GetString("SalesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        internal static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person.
        /// </summary>
        internal static string SalesPerson {
            get {
                return ResourceManager.GetString("SalesPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Quotation.
        /// </summary>
        internal static string SalesQuotation {
            get {
                return ResourceManager.GetString("SalesQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Type.
        /// </summary>
        internal static string SalesType {
            get {
                return ResourceManager.GetString("SalesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save1 {
            get {
                return ResourceManager.GetString("Save1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Party.
        /// </summary>
        internal static string SelectParty {
            get {
                return ResourceManager.GetString("SelectParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Store.
        /// </summary>
        internal static string SelectStore {
            get {
                return ResourceManager.GetString("SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supplier.
        /// </summary>
        internal static string SelectSupplier {
            get {
                return ResourceManager.GetString("SelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Branch.
        /// </summary>
        internal static string SelectYourBranch {
            get {
                return ResourceManager.GetString("SelectYourBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        internal static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        internal static string Shippers {
            get {
                return ResourceManager.GetString("Shippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Maintenance.
        /// </summary>
        internal static string ShippingAddressMaintenance {
            get {
                return ResourceManager.GetString("ShippingAddressMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Charge.
        /// </summary>
        internal static string ShippingCharge {
            get {
                return ResourceManager.GetString("ShippingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Company.
        /// </summary>
        internal static string ShippingCompany {
            get {
                return ResourceManager.GetString("ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Compact.
        /// </summary>
        internal static string ShowCompact {
            get {
                return ResourceManager.GetString("ShowCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Reference.
        /// </summary>
        internal static string StatementReference {
            get {
                return ResourceManager.GetString("StatementReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Types.
        /// </summary>
        internal static string StoreTypes {
            get {
                return ResourceManager.GetString("StoreTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Setup.
        /// </summary>
        internal static string TaxSetup {
            get {
                return ResourceManager.GetString("TaxSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Total.
        /// </summary>
        internal static string TaxTotal {
            get {
                return ResourceManager.GetString("TaxTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Types.
        /// </summary>
        internal static string TaxTypes {
            get {
                return ResourceManager.GetString("TaxTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran Code.
        /// </summary>
        internal static string TranCode {
            get {
                return ResourceManager.GetString("TranCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionDetails {
            get {
                return ResourceManager.GetString("TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Posted Successfully.
        /// </summary>
        internal static string TransactionPostedSuccessfully {
            get {
                return ResourceManager.GetString("TransactionPostedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Status.
        /// </summary>
        internal static string TransactionStatus {
            get {
                return ResourceManager.GetString("TransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measure.
        /// </summary>
        internal static string UnitsOfMeasure {
            get {
                return ResourceManager.GetString("UnitsOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Attachment for This Transaction.
        /// </summary>
        internal static string UploadAttachmentForThisTransaction {
            get {
                return ResourceManager.GetString("UploadAttachmentForThisTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Database.
        /// </summary>
        internal static string VacuumDatabase {
            get {
                return ResourceManager.GetString("VacuumDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Database (Full).
        /// </summary>
        internal static string VacuumFullDatabase {
            get {
                return ResourceManager.GetString("VacuumFullDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Date.
        /// </summary>
        internal static string ValueDate {
            get {
                return ResourceManager.GetString("ValueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Reason.
        /// </summary>
        internal static string VerificationReason {
            get {
                return ResourceManager.GetString("VerificationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified By.
        /// </summary>
        internal static string VerifiedBy {
            get {
                return ResourceManager.GetString("VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View This Invoice.
        /// </summary>
        internal static string ViewThisInvoice {
            get {
                return ResourceManager.GetString("ViewThisInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Verification Policy.
        /// </summary>
        internal static string VoucherVerificationPolicy {
            get {
                return ResourceManager.GetString("VoucherVerificationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Reason.
        /// </summary>
        internal static string WithdrawalReason {
            get {
                return ResourceManager.GetString("WithdrawalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw This Transaction.
        /// </summary>
        internal static string WithdrawThisTransaction {
            get {
                return ResourceManager.GetString("WithdrawThisTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Transaction.
        /// </summary>
        internal static string WithdrawTransaction {
            get {
                return ResourceManager.GetString("WithdrawTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, No.
        /// </summary>
        internal static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
