//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.FrontEnd.Finance.Confirmation {
	
	
	public partial class GLAdvice {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected MixERP.Net.FrontEnd.UserControls.ReportControl GLAdviceReport;
	}
}
