//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.FrontEnd.POS {
	
	
	public partial class AssignCashier {
		
		protected System.Web.UI.WebControls.Content Content1;
	}
}
